environments:
  onprem.production: {}

releases:
  - name: nginx-blue
    namespace: nginx1
    forceNamespace: "nginx1"
    chart: charts/nginx
    installed: true

  - name: nginx-green
    namespace: nginx2
    forceNamespace: "nginx2"
    chart: charts/nginx
    installed: true
