environments:
  onprem.production: {}

releases:
  - name: nginx-blue
    namespace: nginx1
    forceNamespace: "nginx1"
    chart: charts/nginx
    installed: true
    values:
      - cluster: {{ .Environment.Name }}
    secrets:
      - secrets/nginx.yaml

  - name: nginx-green
    namespace: nginx2
    forceNamespace: "nginx2"
    chart: charts/nginx
    installed: true
    values:
      - cluster: {{ .Environment.Name }}
    secrets:
      - secrets/nginx.yaml
